from PySide6.QtWidgets import QMainWindow
from .menubar import build_menubar

class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("CLDL by Chihara Yakou")
        self.setFixedSize(900, 600)
        self.actions = build_menubar(self)

    def action_new_project(self): ...
    def action_open_project(self): ...
    def action_save_project(self): ...
    def action_save_as(self): ...
    def action_import(self): ...
    def action_export_folder(self): ...
    def action_validate(self): ...
    def action_about(self): ...